### ISSUE TITLE
Pysch Syntax Error

### ISSUE THREAD

**Issue by UnderFenex** [jperelli/Redmine-Periodic-Task#105]
Hi, when I run periodictask, using:

/home/user/.rvm/rubies/ruby-2.6.5/bin/bundle exec rake redmine:check_periodictasks RAILS_ENV="production" --trace

I get this error. Any ideas on what it the reason:

```
** Invoke redmine:check_periodictasks (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:check_periodictasks
rake aborted!
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 3 column 7
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:456:in `parse'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:390:in `parse'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:277:in `load'
/home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/coders/yaml_column.rb:26:in `load'
/home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/type/serialized.rb:22:in `deserialize'
/home/user/.rvm/gems/ruby-2.6.5/gems/activemodel-5.2.4.1/lib/active_model/attribute.rb:165:in `type_cast'
/home/user/.rvm/gems/ruby-2.6.5/gems/activemodel-5.2.4.1/lib/active_model/attribute.rb:42:in `value'
/home/user/.rvm/gems/ruby-2.6.5/gems/activemodel-5.2.4.1/lib/active_model/attribute_set.rb:48:in `fetch_value'
/home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/attribute_methods/read.rb:77:in `_read_attribute'
/home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/attribute_methods/read.rb:40:in `__temp__36573747f6d6f5669656c646f56716c6575637'
/var/www/redmine-4.0.6/plugins/periodictask/app/models/periodictask.rb:92:in `fill_custom_fields'
/var/www/redmine-4.0.6/plugins/periodictask/app/models/periodictask.rb:56:in `generate_issue'
/var/www/redmine-4.0.6/plugins/periodictask/lib/scheduled_tasks_checker.rb:9:in `block in checktasks!'
/home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/redmine-4.0.6/plugins/periodictask/lib/scheduled_tasks_checker.rb:4:in `checktasks!'
/var/www/redmine-4.0.6/plugins/periodictask/lib/tasks/periodictask.rake:12:in `block (2 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.5/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.6.5/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:check_periodictasks
```

**Comment by jperelli** [comment]
Try upgrading ruby and the plugin to v5.0.0
