### ISSUE TITLE
rake aborted! Child already added

### ISSUE THREAD

**Issue by Arean82** [jperelli/Redmine-Periodic-Task#121]
Error while while doing bundle exec rake redmine:plugins:migrate RAILS_ENV=production

root@rt:/data/redmine/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /data/redmine)
rake aborted!
Child already added
/data/redmine/lib/redmine/menu_manager.rb:382:in `add_at'
/data/redmine/lib/redmine/menu_manager.rb:309:in `push'
/data/redmine/lib/redmine/plugin.rb:318:in `menu'
/data/redmine/plugins/periodictask/init.rb:21:in `block in <top (required)>'
/data/redmine/lib/redmine/plugin.rb:96:in `instance_eval'
/data/redmine/lib/redmine/plugin.rb:96:in `register'
/data/redmine/plugins/periodictask/init.rb:9:in `<top (required)>'
/data/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/data/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/data/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/data/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in `catch'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `each'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:88:in `prepare!'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
/data/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/3.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.1.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/lib/gems/3.1.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
root@rt:/data/redmine/plugins# rm -rf Redmine-Periodic-Task/
root@rt:/data/redmine/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /data/redmine)

**Comment by Arean82** [comment]
Found the issue had another pluging with the same function
