### ISSUE TITLE
Internal error accessing /projects/<project>/periodictask

### ISSUE THREAD

**Issue by delanym** [jperelli/Redmine-Periodic-Task#122]
I added the periodic task module to my project in Redmine 5.1.3 but when I try navigate there I get an internal error.

```
redmine-1  | I, [2024-09-07T11:57:08.975983 #1]  INFO -- : Started GET "/projects/tep-2-0/periodictask" for 10.1.0.138 at 2024-09-07 11:57:08 +0000
redmine-1  | I, [2024-09-07T11:57:08.978194 #1]  INFO -- : Processing by PeriodictaskController#index as HTML
redmine-1  | I, [2024-09-07T11:57:08.978323 #1]  INFO -- :   Parameters: {"project_id"=>"tep-2-0"}
redmine-1  | I, [2024-09-07T11:57:08.988170 #1]  INFO -- :   Current user: admin.delany (id=74)
redmine-1  | I, [2024-09-07T11:57:09.146341 #1]  INFO -- : Completed 500 Internal Server Error in 168ms (ActiveRecord: 50.0ms | Allocations: 20094)
redmine-1  | F, [2024-09-07T11:57:09.148660 #1] FATAL -- :   
redmine-1  | ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine.periodictasks' doesn't exist):
redmine-1  |   
redmine-1  | plugins/periodictask/app/controllers/periodictask_controller.rb:19:in `index'
redmine-1  | lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by yzzy** [comment]
There's no table in the database. Did you run migration command when installing this plugin?

**Comment by delanym** [comment]
THank you
