### ISSUE TITLE
Redmine 3.1 - uninitialized constant ScheduledTasksChecker::Periodictask

### ISSUE THREAD

**Issue by pztrn** [jperelli/Redmine-Periodic-Task#33]
Trying to install this plugin to redmine 3.1.1, and encounter this error while trying to execute cronjob:

```
** Invoke redmine:check_periodictasks (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:check_periodictasks
rake aborted!
NameError: uninitialized constant ScheduledTasksChecker::Periodictask
/data/redmine/plugins/Redmine-Periodic-Task/lib/scheduled_tasks_checker.rb:3:in `checktasks!'
/data/redmine/plugins/Redmine-Periodic-Task/lib/tasks/periodictask.rake:11:in `block (2 levels) in <top (required)>'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/data/.rbenv/versions/2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/data/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/data/.rbenv/versions/2.1.7/bin/rake:23:in `load'
/data/.rbenv/versions/2.1.7/bin/rake:23:in `<main>'
Tasks: TOP => redmine:check_periodictasks
```

**Comment by jperelli** [comment]
For what I'm seing, I think you have redmine installed inside a rbenv ruby environment, but then you try to install the plugin outside the ruby env.

I think you need to do `rbenv rehash` before plugin installation

Read this: http://stackoverflow.com/questions/9394338/how-do-rvm-and-rbenv-actually-work

**Comment by pztrn** [comment]
Nope, rbenv rehash didn't help. Moreover, I found a solution.

I was followed instructions at http://www.redmine.org/plugins/redmine_periodic_task, but missed requirement of directory naming (it should be exactly ``periodictask``). I want ask you for:

1. Specify this requirement on http://www.redmine.org/plugins/redmine_periodic_task, e.g. with bold text.
2. Make note about it in README more recognizable, e.g. with bold text.

Thanks!

**Comment by jperelli** [comment]
Ok, thanks! I think I'll put a link in redmine's site installation to this repository, because here in readme there was a note about that explicitely, but it was not in redmine's plugin page.
