### ISSUE TITLE
Suddenly rake aborted

### ISSUE THREAD

**Issue by fastuser** [jperelli/Redmine-Periodic-Task#48]
I have just installed this plugin, I did some testing with the cron rake task and all seemed OK. Now 2 days later it seems to fail (could have been right away, not sure)

```
root@linux:/opt/bitnami/apps/redmine/htdocs# sudo rake redmine:check_periodictasks RAILS_ENV="production"
assigning test periodic task
rake aborted!
FloatDomainError: Infinity
/opt/bitnami/apps/redmine/htdocs/plugins/periodictask/lib/scheduled_tasks_checker.rb:33:in `ceil'
/opt/bitnami/apps/redmine/htdocs/plugins/periodictask/lib/scheduled_tasks_checker.rb:33:in `block in checktasks!'
/opt/bitnami/apps/redmine/htdocs/plugins/periodictask/lib/scheduled_tasks_checker.rb:3:in `checktasks!'
/opt/bitnami/apps/redmine/htdocs/plugins/periodictask/lib/tasks/periodictask.rake:11:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:check_periodictasks
(See full trace by running task with --trace)
```

**Comment by fastuser** [comment]
This is my crontab:

```
* 3 * * * /var/backups/redmine-backup.sh > /home/bitnami/redminebu.rpt
*/10 * * * * cd /opt/bitnami/apps/redmine/htdocs/; rake redmine:check_periodictasks RAILS_ENV="production" > /home/bitnami/redminePT.rpt
```

**Comment by jperelli** [comment]
Thanks for the report, I'm seeng that this is because in some place it is dividing by zero, then trying to call .ceil over Infinity. The problem seems to be here https://github.com/jperelli/Redmine-Periodic-Task/blob/master/lib/scheduled_tasks_checker.rb#L42

So when interval_number == 0, this problem arises. Will fix using an `if`
