### ISSUE TITLE
rake : 'development' database is not configured. Available: ["production"]

### ISSUE THREAD

**Issue by grubshka** [jperelli/Redmine-Periodic-Task#71]
After installing Redmine Periodic Tasks plugin, I can't use rake. For example, I needed to regenerate secret token : 
```
redmine@kabuki:~/redmine-git$ bundle exec rake generate_secret_token
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["production"]
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/connection_handling.rb:50:in `establish_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:44:in `each'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
/var/lib/gems/2.1.0/gems/activerecord-4.2.8/lib/active_record/base.rb:26:in `<top (required)>'
/usr/local/share/redmine/redmine-git/lib/plugins/acts_as_activity_provider/init.rb:2:in `block in <top (required)>'
/usr/local/share/redmine/redmine-git/config/initializers/00-core_plugins.rb:12:in `eval'
/usr/local/share/redmine/redmine-git/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
/usr/local/share/redmine/redmine-git/config/initializers/00-core_plugins.rb:2:in `each'
/usr/local/share/redmine/redmine-git/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/usr/local/share/redmine/redmine-git/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/share/redmine/redmine-git/plugins/periodic_task/lib/tasks/periodictask.rake:7:in `<top (required)>'
/usr/local/share/redmine/redmine-git/lib/tasks/redmine.rake:194:in `load'
/usr/local/share/redmine/redmine-git/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/usr/local/share/redmine/redmine-git/lib/tasks/redmine.rake:194:in `each'
/usr/local/share/redmine/redmine-git/lib/tasks/redmine.rake:194:in `<top (required)>'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `load'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.1.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/share/redmine/redmine-git/Rakefile:7:in `<top (required)>'
/var/lib/gems/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by jperelli** [comment]
It seems that you have not configured the development environment right.

try this command instead
```
RAILS_ENV=production bundle exec rake generate_secret_token
```
